<a href="https://colab.research.google.com/github/aadhiadvaitha/Image-Classification/blob/main/MinorProject.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install bing-image-downloader

In [2]:
!mkdir images

In [3]:
#gathering data
from bing_image_downloader import downloader
downloader.download("Elephant",limit=50,output_dir='images', adult_filter_off=True)



[!!]Indexing page: 1

[%] Indexed 12 Images on Page 1.


[%] Downloading Image #1 from http://naibuzz.com/wp-content/uploads/2017/03/3EC4B13E00000578-0-image-a-56_1490866924185.jpg
[%] File Downloaded !

[%] Downloading Image #2 from http://www.indonesia-tourism.com/north-sumatra/images/zoo.jpg
[%] File Downloaded !

[%] Downloading Image #3 from https://thumbs.dreamstime.com/z/sunflowers-vase-25740611.jpg
[%] File Downloaded !

[%] Downloading Image #4 from https://img.elephantjournal.com/wp-content/uploads/2014/01/Solitude.jpg
[%] File Downloaded !

[%] Downloading Image #5 from https://hative.com/wp-content/uploads/2014/10/pumpkin-carving-ideas/30-wine-cooler-pumpkin.jpg
[%] File Downloaded !

[%] Downloading Image #6 from http://www.adias-uae.com/images/Miocene (elephants, giraffe).jpg
[!] Issue getting: http://www.adias-uae.com/images/Miocene (elephants, giraffe).jpg
[!] Error:: URL can't contain control characters. '/images/Miocene (elephants, giraffe).jpg' (found at least ' ')

In [4]:
from bing_image_downloader import downloader
downloader.download("Giraffe",limit=50,output_dir='images', adult_filter_off=True)



[!!]Indexing page: 1

[%] Indexed 12 Images on Page 1.


[%] Downloading Image #1 from https://www.quickanddirtytips.com/sites/default/files/images/8641/giraffe.jpg
[%] File Downloaded !

[%] Downloading Image #2 from http://wwf.worldwildlife.org/images/content/pagebuilder/41625_Panda2_iphone6.jpg
[%] File Downloaded !

[%] Downloading Image #3 from https://www.zooborns.com/.a/6a010535647bf3970b016766b8015d970b-600wi
[%] File Downloaded !

[%] Downloading Image #4 from https://summervacationsin.com/wp-content/uploads/2016/11/11-kenya-vacations-best-places-visit-4.jpg
[%] File Downloaded !

[%] Downloading Image #5 from http://www.lorihough.com/Pictures/GiraffeArmature.JPG
[%] File Downloaded !

[%] Downloading Image #6 from https://www.wallpapers13.com/wp-content/uploads/2016/02/Wonderful-Wild-Horses-Wide-High-Resolution-Wallpaper-For-Desktop-Background.jpg
[%] File Downloaded !

[%] Downloading Image #7 from https://babyshowerideas4u.com/wp-content/uploads/2015/05/Bright-Yellow-Gira

In [5]:
#preprocessing
import pandas as pd
import matplotlib.pyplot as plt
from skimage.io import imread
from skimage.transform import resize
import os
import numpy as np
datadir = '/content/images'

target = []
images=[]
flat_data = []
#0 means elephant and 1 means giraffe
CATEGORIES = ['Elephant','Giraffe']
for category in CATEGORIES:
  class_num=CATEGORIES.index(category)
  path = os.path.join(datadir,category)
  
  for img in os.listdir(path):
    img_array = imread(os.path.join(path,img))
    img_resized = resize(img_array,(150,150,3)) 
    flat_data.append(img_resized.flatten())
    images.append(img_resized)
    target.append(class_num) 

flat_data = np.array(flat_data)
target = np.array(target)
images=np.array(images)

In [6]:
#flattening
df = pd.DataFrame(flat_data)
df['Target'] = target
df.head()

0         1         2         3  ...     67497     67498     67499  Target
0  0.695425  0.697499  0.403651  0.718458  ...  0.499817  0.407190  0.285752       0
1  0.082773  0.078431  0.058824  0.043837  ...  0.760784  0.756863  0.776471       0
2  0.000000  0.023137  0.168627  0.001059  ...  0.893725  0.752157  0.321529       0
3  0.494118  0.509804  0.513725  0.501961  ...  0.062745  0.023529  0.054902       0
4  0.755366  0.755366  0.755366  0.866471  ...  0.674392  0.672431  0.671771       0

[5 rows x 67501 columns]

In [7]:
flat_data

array([[0.69542484, 0.69749891, 0.40365142, ..., 0.49981699, 0.40718954,
        0.28575163],
       [0.08277333, 0.07843137, 0.05882353, ..., 0.76078431, 0.75686275,
        0.77647059],
       [0.        , 0.02313725, 0.16862745, ..., 0.89372549, 0.75215686,
        0.32152941],
       ...,
       [0.69019608, 0.50490196, 0.30980392, ..., 0.49803922, 0.37647059,
        0.26176471],
       [1.        , 1.        , 1.        , ..., 1.        , 1.        ,
        1.        ],
       [0.53950327, 0.54342484, 0.52381699, ..., 0.39372113, 0.44927669,
        0.28962092]])

In [8]:
target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [9]:
np.unique(target,return_counts=True)

(array([0, 1]), array([50, 50]))

In [10]:
#SVM using GridSearch CV
from sklearn.model_selection import GridSearchCV
from sklearn import svm
param_grid = [
             {'C':[1,10,100,1000],'kernel':['linear']}, 
            {'C':[1,10,100,1000],'gamma':[0.001,0.0001],'kernel':['rbf']}
]
svc=svm.SVC(probability=True)
dev=GridSearchCV(svc,param_grid)
dev.fit(x_train,y_train)

NameError: ignored

In [ ]:
abc=svm.SVC(kernel='rbf',C=1,gamma='scale',random_state=0)

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(flat_data,target,test_size=0.3,random_state=0)


In [ ]:
y_pred=dev.predict(x_test)
y_pred

In [ ]:
y_test

In [ ]:
#accuracy score
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
accuracy_score(y_pred,y_test)

In [ ]:
#classification report
print(classification_report(y_pred,y_test))

In [ ]:
#confusion matrix
confusion_matrix(y_pred,y_test)

In [ ]:
#cross validation
from sklearn.model_selection import cross_val_score
from sklearn.svm import SVC
cross_val_score(SVC(),x_train,y_train)

In [ ]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=10,random_state=1,shuffle=True)
print(kf)

In [ ]:
#accuracy score after cross validation
accuracy=cross_val_score(abc,x_train,y_train,scoring='accuracy',cv=10)
print(accuracy)
mean=np.mean(accuracy)
print(mean)

In [ ]:
import pickle
pickle.dump(dev,open('img_model.p','wb'))

In [ ]:
abc.fit(x_train,y_train)
ypred=abc.predict(x_test)
print(ypred)
print(y_test)
accuracy_score(ypred,y_test)

In [ ]:
#prediction for new image
# 0 is Elephant and 1 is Giraffe
model1=pickle.load(open('img_model.p','rb'))
flat_data=[]
url=input('Enter your URL')
img=imread(url)
img_resized=resize(img,(150,150,3))
flat_data.append(img_resized.flatten())
flat_data=np.array(flat_data)
print (img.shape)
plt.imshow(img_resized)
y_output=model1.predict(flat_data)
y_output
print(f'Predicted Output: {y_output}')
